version: '3.7'
services:
  mongodb_container:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


  terragrunt_container:
    container_name: devopsinfra
    build: 
      context: ./docker-terragrunt
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - /mnt/d/dockers/devopsinfra:/data  

volumes:
  mongodb_data_container:
  # devopsinfra_data_container:
  

# docker volume create --name=mongodb_data_container
# docker volume create --name=devopsinfra_data_container


# docker exec -it couchdb_container /bin/bash
# docker-compose up -d couchdb_container
# docker-compose up --build couchdb_container

# docker network create hadleynet
# docker network connect hadleynet devopsinfra
# docker network connect hadleynet hadley_mongodb_container_1
# docker network inspect hadleynet